services:
  demo-app:
    build: .
    volumes:
      - .:/src
      - .dockervenv:/src/.venv
    ports:
      - "8000:8000"
    environment:
      - WATCHFILES_FORCE_POLLING=true
  db:
    image: mysql:8.0
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes' # root 비밀번호 없이 생성
      MYSQL_DATABASE: 'demo' # 초기 데이터베이스
      TZ: 'Asia/Seoul' # 타임존 설정
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    # MySQL8.0에서는 기본값이
    # 'caching_sha2_password'이라 드라이버가 비지원으로 변경
    ports:
      - "33306:3306" # 호스트 머신의 33306번 포트를 docker의 3306번 포트에 연결
volumes:
  mysql_data: